[package]
name = "dollis"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
rust-version = "1.65"

[dependencies]
bevy = { version = "0.9", default-features = false, features = [
  "bevy_gltf",
  "filesystem_watcher",
  "png",
  "x11",
] }
bevy_renet = "0.0.6"
bevy_rapier3d = "0.20"
bevy_mod_raycast = { version = "0.7", default-features = false }
bevy_mod_outline = { version = "0.3", default-features = false }
bevy_egui = "0.17"
bevy_polyline = { git = "https://github.com/dollisgame/bevy_polyline", branch = "remove-render-feature-0.9" }
bevy-hikari = "0.3"
bevy-inspector-egui = { version = "0.14", default-features = false, features = [
  "clipboard",
  "bevy_pbr",
] }
bevy-scene-hook = "5.1"
iyes_loopless = "0.9"
bevy-trait-query = "0.1"
leafwing-input-manager = { version = "0.7", default-features = false, features = [
  "egui",
] }
serde = "1.0"
strum = { version = "0.24", features = ["derive"] }
derive_more = { version = "0.99", default-features = false, features = [
  "constructor",
] }
standard_paths = "2.0"
clap = { version = "4.0", features = ["derive"] }
anyhow = "1.0"
toml = "0.5"
rmp-serde = "1.1"
ron = "0.8"
tap = "1.0"
smallvec = "1.10"
walkdir = "2.3"
itertools = "0.10"

[dev-dependencies]
fastrand = "1.8.0"
serde_test = "1.0"

# Enable high optimizations for dependencies, but not for our code:
[profile.dev.package."*"]
opt-level = 3
