[package]
name = "lifescape"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
rust-version = "1.65"

[dependencies]
bevy = { version = "0.12.1", default-features = false, features = [
  "animation",
  "bevy_gltf",
  "bevy_ui",
  "bevy_sprite",
  "bevy_text",
  "file_watcher",
  "png",
  "x11",
] }
bevy_atmosphere = "0.8"
bevy_replicon = "0.18"
bevy_rapier3d = "0.23"
bevy_mod_outline = "0.6"
bevy_polyline = { git = "https://github.com/rszemplinski/bevy_polyline" }
app_dirs2 = "2.5"
oxidized_navigation = { version = "0.8", features = ["rapier"] }
leafwing-input-manager = "0.11"
serde = "1.0"
strum = { version = "0.25", features = ["derive"] }
num_enum = "0.7"
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
toml = "0.7"
bincode = "1.3"
ron = "0.8"
walkdir = "2.4"
itertools = "0.12"
bitflags = "2.4"
futures-lite = "1.13"
