[package]
name = "lifescape"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0-or-later"
rust-version = "1.65"

[dependencies]
bevy = { version = "0.11", default-features = false, features = [
  "animation",
  "bevy_gltf",
  "bevy_ui",
  "bevy_sprite",
  "bevy_text",
  "filesystem_watcher",
  "png",
  "x11",
] }
bevy_atmosphere = "0.7"
bevy_replicon = "0.9"
bevy_rapier3d = "0.22"
bevy_mod_outline = { git = "https://github.com/ramirezmike/bevy_mod_outline", default-features = false }
bevy_polyline = "0.7"
oxidized_navigation = "0.6"
leafwing-input-manager = "0.10"
serde = "1.0"
strum = { version = "0.25", features = ["derive"] }
num_enum = "0.6"
derive_more = { version = "0.99", default-features = false, features = [
  "constructor",
] }
standard_paths = "2.1"
clap = { version = "4.3", features = ["derive"] }
anyhow = "1.0"
toml = "0.7"
bincode = "1.3"
ron = "0.8"
smallvec = "1.11"
walkdir = "2.3"
itertools = "0.11"
bitflags = "2.3"
futures-lite = "1.13"

[dev-dependencies]
fastrand = "1.9"
serde_test = "1.0"

[patch.crates-io]
bevy_a11y = { git = "https://github.com/lifescapegame/bevy", branch = "0.11.0-patched" }
bevy_animation = { git = "https://github.com/lifescapegame/bevy", branch = "0.11.0-patched" }
bevy_app = { git = "https://github.com/lifescapegame/bevy", branch = "0.11.0-patched" }
bevy_asset = { git = "https://github.com/lifescapegame/bevy", branch = "0.11.0-patched" }
bevy_core = { git = "https://github.com/lifescapegame/bevy", branch = "0.11.0-patched" }
bevy_core_pipeline = { git = "https://github.com/lifescapegame/bevy", branch = "0.11.0-patched" }
bevy_derive = { git = "https://github.com/lifescapegame/bevy", branch = "0.11.0-patched" }
bevy_diagnostic = { git = "https://github.com/lifescapegame/bevy", branch = "0.11.0-patched" }
bevy_ecs = { git = "https://github.com/lifescapegame/bevy", branch = "0.11.0-patched" }
bevy_encase_derive = { git = "https://github.com/lifescapegame/bevy", branch = "0.11.0-patched" }
bevy_gilrs = { git = "https://github.com/lifescapegame/bevy", branch = "0.11.0-patched" }
bevy_gltf = { git = "https://github.com/lifescapegame/bevy", branch = "0.11.0-patched" }
bevy_hierarchy = { git = "https://github.com/lifescapegame/bevy", branch = "0.11.0-patched" }
bevy_input = { git = "https://github.com/lifescapegame/bevy", branch = "0.11.0-patched" }
bevy_internal = { git = "https://github.com/lifescapegame/bevy", branch = "0.11.0-patched" }
bevy_log = { git = "https://github.com/lifescapegame/bevy", branch = "0.11.0-patched" }
bevy_macro_utils = { git = "https://github.com/lifescapegame/bevy", branch = "0.11.0-patched" }
bevy_math = { git = "https://github.com/lifescapegame/bevy", branch = "0.11.0-patched" }
bevy_mikktspace = { git = "https://github.com/lifescapegame/bevy", branch = "0.11.0-patched" }
bevy_pbr = { git = "https://github.com/lifescapegame/bevy", branch = "0.11.0-patched" }
bevy_ptr = { git = "https://github.com/lifescapegame/bevy", branch = "0.11.0-patched" }
bevy_reflect = { git = "https://github.com/lifescapegame/bevy", branch = "0.11.0-patched" }
bevy_render = { git = "https://github.com/lifescapegame/bevy", branch = "0.11.0-patched" }
bevy_scene = { git = "https://github.com/lifescapegame/bevy", branch = "0.11.0-patched" }
bevy_tasks = { git = "https://github.com/lifescapegame/bevy", branch = "0.11.0-patched" }
bevy_time = { git = "https://github.com/lifescapegame/bevy", branch = "0.11.0-patched" }
bevy_transform = { git = "https://github.com/lifescapegame/bevy", branch = "0.11.0-patched" }
bevy_utils = { git = "https://github.com/lifescapegame/bevy", branch = "0.11.0-patched" }
bevy_window = { git = "https://github.com/lifescapegame/bevy", branch = "0.11.0-patched" }
bevy_winit = { git = "https://github.com/lifescapegame/bevy", branch = "0.11.0-patched" }
