[licenses]
allow = [
  "AGPL-3.0",
  "MIT",
  "MIT-0",
  "BSL-1.0",
  "OFL-1.1",
  "LicenseRef-UFL-1.0",
  "Apache-2.0",
  "BSD-3-Clause",
  "ISC",
  "Zlib",
  "BSD-2-Clause",
  "CC0-1.0",
  "Unicode-3.0",
]

[advisories]
ignore = ["RUSTSEC-2024-0384"]

[bans]
skip-tree = ["bevy"]

[sources]
unknown-git = "allow"
