[advisories]
unmaintained = "deny"
yanked = "deny"
notice = "deny"
unsound = "deny"
ignore = ["RUSTSEC-2020-0168", "RUSTSEC-2022-0048"]

[licenses]
copyleft = "allow"
allow-osi-fsf-free = "either"
allow = ["LicenseRef-UFL-1.0"] # For Ubuntu Light font from egui.

[[licenses.clarify]]
name = "stretch"
expression = "MIT"
license-files = []

[bans]
multiple-versions = "deny"
wildcards = "allow"
skip = [
  { name = "syn", version = "1.0" },
  { name = "ahash", version = "0.7.6" },
  { name = "memoffset", version = "0.6.5" },
  { name = "nix", version = "0.24" },
  { name = "redox_syscall", version = "0.2" },
  { name = "windows-sys", version = "0.42" },
  { name = "windows-sys", version = "0.45" },
  { name = "windows", version = "0.43" },
  { name = "windows_x86_64_msvc", version = "0.42" },
  { name = "windows_x86_64_gnullvm", version = "0.42" },
  { name = "windows_x86_64_gnu", version = "0.42" },
  { name = "windows_i686_msvc", version = "0.42" },
  { name = "windows_i686_gnu", version = "0.42" },
  { name = "windows_aarch64_msvc", version = "0.42" },
  { name = "windows_aarch64_gnullvm", version = "0.42" },
  { name = "windows-targets", version = "0.42" },
]

[sources]
unknown-registry = "deny"
unknown-git = "allow"
