[licenses]
allow = [
  "AGPL-3.0",
  "MIT",
  "MIT-0",
  "BSL-1.0",
  "OFL-1.1",
  "LicenseRef-UFL-1.0",
  "Apache-2.0",
  "BSD-3-Clause",
  "ISC",
  "Zlib",
  "BSD-2-Clause",
  "CC0-1.0",
  "Unicode-DFS-2016",
]

[bans]
multiple-versions = "deny"
wildcards = "allow"
skip = [
  { name = "base64", version = "0.21" },
  { name = "bitflags", version = "1.3" },
  { name = "cfg_aliases", version = "0.1" },
  { name = "event-listener-strategy", version = "0.4" },
  { name = "event-listener", version = "<5.1" },
  { name = "fixedbitset", version = "0.4" },
  { name = "heck", version = "0.4" },
  { name = "image", version = "0.24" },
  { name = "itertools", version = "0.11" },
  { name = "libloading", version = "0.7" },
  { name = "ndk-sys", version = "0.5" },
  { name = "regex-automata", version = "0.1" },
  { name = "regex-syntax", version = "0.6" },
  { name = "syn", version = "1.0" },
  { name = "toml_edit", version = "0.21" },
  { name = "windows_aarch64_gnullvm" },
  { name = "windows_aarch64_msvc" },
  { name = "windows_i686_gnu" },
  { name = "windows_i686_msvc" },
  { name = "windows_x86_64_gnu" },
  { name = "windows_x86_64_gnullvm" },
  { name = "windows_x86_64_msvc" },
  { name = "windows-core" },
  { name = "windows-sys" },
  { name = "windows-targets" },
  { name = "windows" },
  { name = "winnow", version = "0.5" },
]

[sources]
unknown-registry = "deny"
unknown-git = "allow"
